global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'api-gateway'
          environment: 'development'

  - job_name: 'product-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          application: 'product-service'
          environment: 'development'

  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']
        labels:
          application: 'order-service'
          environment: 'development'

  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8083']
        labels:
          application: 'payment-service'
          environment: 'development'

  - job_name: 'inventory-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8084']
        labels:
          application: 'inventory-service'
          environment: 'development'

  - job_name: 'shipping-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8085']
        labels:
          application: 'shipping-service'
          environment: 'development'

  - job_name: 'customer-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8086']
        labels:
          application: 'customer-service'
          environment: 'development'

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8087']
        labels:
          application: 'notification-service'
          environment: 'development'

  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']
        labels:
          application: 'tempo'

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
        labels:
          application: 'loki'
